---
- name: Stop and disable NetworkManager
  systemd:
    name: NetworkManager
    enabled: no
    state: stopped

- name: Start and enable network
  systemd:
    name: network
    enabled: yes
    state: started

# TODO: Create partition for cinder-volumes if it does not already exist

- name: Create the cinder-volumes volume group
  lvg:
    vg: cinder-volumes
    pvs: /dev/sda4
    state: present

- name: Copy packstack answers file
  copy:
    src: packstack-answers.txt
    dest: /root/packstack-answers.txt

- name: Run packstack
  command: packstack --answer-file=packstack-answers.txt
