---
- name: Stop and disable NetworkManager
  systemd:
    name: NetworkManager
    enabled: no
    state: stopped

- name: Start and enable network
  systemd:
    name: network
    enabled: yes
    state: started

- name: Create the cinder-volumes partition
  parted:
    device: /dev/sda
    name: cinder-volumes
    number: 4
    part_start: 77618176.0KiB
    part_end: 182475776.0KiB
    part_type: primary
    state: present
    flags: [lvm]

- name: Create the cinder-volumes volume group
  lvg:
    vg: cinder-volumes
    pvs: /dev/sda4
    state: present

- name: Create the swift storage partition
  parted:
    device: /dev/sda
    name: swift-storage
    number: 5
    part_end: 100%
    part_start: 187GB
    part_type: primary
    state: present

- name: Create the swift storage filesystem
  filesystem:
    dev: /dev/sda5
    fstype: xfs
    resizefs: yes

- name: Copy packstack answers file
  copy:
    src: packstack-answers.txt
    dest: /root/packstack-answers.txt

- name: Run packstack
  command: packstack --answer-file=packstack-answers.txt
