galaxy_info:
  author: Jason DeTiberus
  description: OpenStack Control Host configuration for portable lab
  license: Apache License 2.0
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
    - 7
  galaxy_tags: []
dependencies: []
